### PR TITLE
Accept null dlhandle and support custom dlopen flags

### PR DESCRIPTION
**Pull request by chapulina**
After digging through #30, ~~I was able to get `ign-sensors` to work with only this change, without touching the local / global variables. It seems to me that this change is backwards compatible, because it only tries the nullptr after trying the usual method first.~~ *Update*: this PR also allows changing setting to global.

We know no previous use cases were getting a null handle because we haven't run into that assert. So I think this is safe to go into `ign-plugin1`.

Unfortunately, I have no idea what leads us into this situation, so I'm not able to write a test case for it :confused: 

Let me know what you think, @ahcorde .

Here's the `ign-sensors` PR that uses this: https://github.com/ignitionrobotics/ign-sensors/pull/90

### CODE REVIEW

**Comment by ahcorde** [comment]
I made a cimment about this here https://github.com/ignitionrobotics/ign-sensors/pull/90#issuecomment-774103025

**Comment by chapulina** [comment]
> I made a cimment about this here

@ahcorde , I think the current version of this PR addresses those test failures. This PR adds support for `RTLD_GLOBAL` just like #30 does, with the advantage of:

* not requiring a version bump
* allowing the flexibility of not applying the change to all libraries
* allowing the flexibility of restoring the `RTLD_LOCAL` behaviour in the future if we want

Let me know what you think.

**Review by ahcorde — APPROVED** [review]

**Review by nkoenig — APPROVED** [review]

**Comment by chapulina** [comment]
I started writing some tests using `RLTD_GLOBAL` in 54e2981 and it's not looking good. Tests crash on shutdown, crash when loading libraries depending on the flag combination.

I'm afraid that we get this in, start using `RTLD_GLOBAL`, and start seeing runtime failures throughout the stack.

**Comment by chapulina** [comment]
Removing beta label, we won't have time to wrap this up before code freeze. Let's retarget at Ignition-F.

**Comment by chapulina** [comment]
Let's table this idea for now, tweaking the flags is probably not the best way to go about this.

**Pull request closed without merging**
